name: dispatch_workflow

on:
  workflow_dispatch:
    inputs:
      discounted_interest_training:
        type: boolean
        required: true
      table_suffix:
        type: string
        required: false

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "table_suffix: \"${{ inputs.table_suffix }}\"" #（通常は空文字列）
          echo "discounted_interest_training: \"${{ inputs.discounted_interest_training }}\"" #（引き下げ金利モデルを学習するときはtrue）
